### ISSUE TITLE
DataFrame.show not convinient for bigger columns

### ISSUE THREAD

**Issue by datanikkthegreek** [Eventual-Inc/Daft#3996]
### Is your feature request related to a problem?

Yes, When having a column with a lot of content it's really hard to navigate.

![Image](https://github.com/user-attachments/assets/ee5af2da-7af3-45b4-85c4-a3401125aae6)

### Describe the solution you'd like

An option could be that you allow the user to decide if a column should be truncated.

In this case I would like instead of the scrollbars that the row and column just increase sothat everything is visible.

See also Spark. https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.show.html

I know I am referencing Spark in my issues always :) But those are things which work really nicely there. Of course I am aware it takes time. :) 

### Describe alternatives you've considered

None

### Would you like to implement a fix?

No

**Comment by jaychia** [comment]
Thanks @datanikkthegreek !

We implemented this because of some egregiously long strings (eg if you're reading markdown files in each row)

Thoughts if instead maybe we built in a way that when you click on a cell/row it could give a blown-up view as a popup perhaps?

**Comment by datanikkthegreek** [comment]
@jaychia thanks for the suit reply. 

I understand due to the multimodal use case you have on your side. If you make the user of course decide if columns should be truncated or not with default False of course you still have the case covered.

That's also on option. Then you could see everything. I am just thinking if people might want to copy things out of the cell. Then it's not that convenient. Maybe there is an option where you can pull a cell open and adjust it. I think in Databricks you can do it. Columnwise at least.

**Comment by rchowell** [comment]
@datanikkthegreek I have a PR which adds more .show options. The default behavior is to truncate like today, but you can set `.show(max_width=None)` which will not truncate the columns. You may also give per-column options, like 

```python
# don't truncate
df.show(max_width=None)

# truncate first column to 12 chars, and don't truncate the second column
df.show(columns=[{ "max_width": 12 }, { "max_width": None } ])
```

https://github.com/Eventual-Inc/Daft/pull/4100

**Comment by datanikkthegreek** [comment]
@rchowell awesome... Any chance to have a pre release version to give it a quick spin for a feedback? :)

**Comment by datanikkthegreek** [comment]
Otherwise really amazing. I love the approach.
